#!/bin/bash

iozone -i 0 -i 1 -i 2 -s 10g -t 1 -r 16m -I >> 10GB16MB
iozone -i 0 -i 1 -i 2 -s 10g -t 1 -r 1m -I >> 10GB1MB
iozone -i 0 -i 1 -i 2 -s 10g -t 1 -r 64k -I >> 10GB64B

iozone -i 0 -i 1 -i 2 -s 5g -t 2 -r 16m -I >> 5GB16MB
iozone -i 0 -i 1 -i 2 -s 5g -t 2 -r 1m -I >> 5GB1MB
iozone -i 0 -i 1 -i 2 -s 5g -t 2 -r 64k -I >> 5GB64KB

iozone -i 0 -i 1 -i 2 -s 2.5g -t 4 -r 16m -I >> 2.5GB16MB
iozone -i 0 -i 1 -i 2 -s 2.5g -t 4 -r 1m -I >> 2.5GB1MB
iozone -i 0 -i 1 -i 2 -s 2.5g -t 4 -r 64k -I >> 2.5GB64KB

iozone -i 0 -i 1 -i 2 -s 1.25g -t 8 -r 16m -I >> 1.25GB16MB
iozone -i 0 -i 1 -i 2 -s 1.25g -t 8 -r 1m -I >> 1.25GB1MB
iozone -i 0 -i 1 -i 2 -s 1.25g -t 8 -r 64k -I >> 1.25GB64KB

iozone -i 0 -i 1 -i 2 -s 833.33m -t 12 -r 16m -I >> 833MB16MB
iozone -i 0 -i 1 -i 2 -s 833.33m -t 12 -r 1m -I >> 833MB1MB
iozone -i 0 -i 1 -i 2 -s 833.33m -t 12 -r 64k -I >> 833MB64KB

iozone -i 0 -i 1 -i 2 -s 416.67m -t 24 -r 16m -I >> 416MB16MB
iozone -i 0 -i 1 -i 2 -s 416.67m -t 24 -r 1m -I >> 416MB1MB
iozone -i 0 -i 1 -i 2 -s 416.67m -t 24 -r 64k -I >> 416MBB64KB

iozone -i 0 -i 1 -i 2 -s 208.33m -t 48 -r 16m -I >> 208MB16MB
iozone -i 0 -i 1 -i 2 -s 208.33m -t 48 -r 1m -I >> 208MB1MB
iozone -i 0 -i 1 -i 2 -s 208.33m -t 48 -r 64k -I >> 208MB64KB

iozone -i 0  -i 2 -s 208.33m -t 48 -r 4k -I -O >> 208MB4KB
iozone -i 0  -i 2 -s 416.67m -t 24 -r 4k -I -O >> 416MB4KB
iozone -i 0  -i 2 -s 833.33m -t 12 -r 4k -I -O >> 833MB4KB

iozone -i 0 -i 2 -s 1.25g -t 8 -r 4k -I -O >> 1.25GB4KB
iozone -i 0 -i 2 -s 2.5g -t 4 -r 4k -I -O >> 2.5GB4KB
iozone -i 0 -i 2 -s 5g -t 2 -r 4k -I -O >> 5GB4KB
iozone -i 0 -i 2 -s 10g -t 1 -r 4k -I -O >> 10GB4KB
